# Generated by Django 4.2.5 on 2025-10-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='status',
            field=models.CharField(default='Not Activated', max_length=100),
        ),
    ]
