# Generated by Django 4.2.5 on 2025-10-12 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userregistration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merkle_root', models.CharField(blank=True, max_length=128, null=True)),
                ('merkle_hmac', models.CharField(blank=True, max_length=128, null=True)),
                ('master_salt', models.BinaryField(blank=True, null=True)),
                ('filesize', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('encrypted_data', models.FileField(upload_to=users.models.shard_upload_path)),
                ('nonce', models.BinaryField()),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('hash_hex', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shards', to='users.document')),
            ],
        ),
        migrations.CreateModel(
            name='ShardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shard_index', models.PositiveSmallIntegerField()),
                ('key_hash', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shardkeys', to='users.document')),
            ],
        ),
    ]
