# Generated by Django 4.2.5 on 2025-10-12 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document_shardkey_shard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('key_generation_time', models.FloatField(default=0.0)),
                ('encryption_time', models.FloatField(default=0.0)),
                ('decryption_time', models.FloatField(default=0.0)),
                ('response_time', models.FloatField(default=0.0)),
                ('computational_overhead', models.FloatField(default=0.0)),
                ('total_change_rate', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='users.document')),
            ],
        ),
    ]
