# Generated by Django 4.2.5 on 2025-10-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_onetimekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimekey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration'),
        ),
    ]
