# Generated by Django 4.2.5 on 2025-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_onetimekey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='Document',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
