# Generated by Django 6.0.2 on 2026-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userregistration_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='institution_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='status',
            field=models.CharField(default='Activated', max_length=100),
        ),
    ]
