# Generated by Django 6.0.2 on 2026-02-05 08:52

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_enhance_admin_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='status',
            field=models.CharField(default='Activated', max_length=100),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.resume_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File extension (pdf, docx, etc.)', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.userregistration')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(default='AI', help_text='Type of analysis performed', max_length=20)),
                ('status', models.CharField(default='PENDING', help_text='Analysis status', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='users.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Category (e.g., 'Programming', 'Soft Skills')", max_length=50)),
                ('keyword', models.CharField(help_text='Keyword or phrase', max_length=100)),
                ('weight', models.FloatField(default=1.0, help_text='Weight for scoring (0.1-5.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'keyword'],
                'unique_together': {('category', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ResumeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall resume score (0-100)')),
                ('skills_score', models.FloatField(default=0.0, help_text='Skills relevance score')),
                ('experience_score', models.FloatField(default=0.0, help_text='Experience quality score')),
                ('education_score', models.FloatField(default=0.0, help_text='Education relevance score')),
                ('format_score', models.FloatField(default=0.0, help_text='Resume format score')),
                ('keywords_score', models.FloatField(default=0.0, help_text='Keywords relevance score')),
                ('skills_analysis', models.TextField(blank=True, help_text='AI analysis of skills')),
                ('experience_analysis', models.TextField(blank=True, help_text='AI analysis of experience')),
                ('education_analysis', models.TextField(blank=True, help_text='AI analysis of education')),
                ('format_analysis', models.TextField(blank=True, help_text='AI analysis of format')),
                ('keywords_analysis', models.TextField(blank=True, help_text='AI analysis of keywords')),
                ('strengths', models.TextField(blank=True, help_text='Identified strengths')),
                ('improvements', models.TextField(blank=True, help_text='Suggested improvements')),
                ('recommendations', models.TextField(blank=True, help_text='Specific recommendations')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in rating (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='users.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
