# Generated by Django 6.0.2 on 2026-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_resume_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerating',
            name='analysis_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='analysis_version',
            field=models.CharField(default='1.0', help_text='Version of analysis algorithm', max_length=20),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='bullet_points',
            field=models.IntegerField(default=0, help_text='Number of bullet points found'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Total character count in resume'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='contact_methods',
            field=models.IntegerField(default=0, help_text='Number of contact methods found'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='education_level',
            field=models.CharField(blank=True, help_text='Highest education level detected', max_length=50),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='experience_years',
            field=models.FloatField(default=0.0, help_text='Years of experience detected'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Extracted text from resume'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='skills_found',
            field=models.JSONField(blank=True, default=dict, help_text='Skills identified in resume'),
        ),
        migrations.AddField(
            model_name='resumerating',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Total word count in resume'),
        ),
    ]
