# Generated by Django 6.0.2 on 2026-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_resumerating_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_company',
            field=models.CharField(blank=True, help_text='Target company for analysis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, help_text='Target job role for analysis', max_length=100, null=True),
        ),
    ]
