# Generated by Django 6.0.2 on 2026-02-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_resume_target_company_resume_target_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='target_company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='target_role',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='academic_marks',
            field=models.FloatField(blank=True, help_text='Academic marks percentage (for students only)', null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='college_name',
            field=models.CharField(blank=True, help_text='College/University name (for students only)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID (for students only)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('non_student', 'Non Student')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='year_and_branch',
            field=models.CharField(blank=True, help_text='Year and Branch (e.g., 3rd Year B.Tech CSE)', max_length=100, null=True),
        ),
    ]
