# Generated by Django 6.0.2 on 2026-02-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_resume_target_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='year_and_branch',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch/Specialization (for students only)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='year',
            field=models.CharField(blank=True, help_text='Academic Year (for students only)', max_length=20, null=True),
        ),
    ]
