# Generated by Django 6.0.2 on 2026-02-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_userregistration_year_and_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysislog',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_logs', to='users.resume'),
        ),
    ]
