# Generated by Django 6.0.2 on 2026-02-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_resumeanalysislog_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mock Test Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='shard',
            name='document',
        ),
        migrations.RemoveField(
            model_name='shardkey',
            name='document',
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes')),
                ('total_questions', models.IntegerField(default=0)),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score to pass')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.mocktestcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for multiple choice')),
                ('correct_answer', models.IntegerField(help_text='Index of correct answer in options')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0, help_text='Order of question in test')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, help_text='Target role for this test attempt', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timeout', 'Timeout')], default='in_progress', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('unanswered', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('total_points', models.IntegerField(default=0)),
                ('earned_points', models.IntegerField(default=0)),
                ('performance_level', models.CharField(blank=True, max_length=50)),
                ('feedback_message', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_results', to='users.userregistration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(blank=True, help_text='Index of selected answer', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken for this question in seconds', null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mocktestquestion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.mocktestresult')),
            ],
            options={
                'ordering': ['question__order', 'question__id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('current_question', models.IntegerField(default=0)),
                ('time_remaining', models.IntegerField(help_text='Time remaining in seconds')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='users.mocktestresult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_sessions', to='users.userregistration')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentKeyRequest',
        ),
        migrations.DeleteModel(
            name='Shard',
        ),
        migrations.DeleteModel(
            name='ShardKey',
        ),
        migrations.AddIndex(
            model_name='mocktestresult',
            index=models.Index(fields=['user', '-started_at'], name='users_mockt_user_id_15cc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestresult',
            index=models.Index(fields=['test', '-started_at'], name='users_mockt_test_id_c240b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestresult',
            index=models.Index(fields=['status'], name='users_mockt_status_5f46ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktestanswer',
            unique_together={('result', 'question')},
        ),
    ]
