# Generated by Django 6.0.2 on 2026-02-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_mocktestcategory_remove_shard_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('test_index', models.IntegerField()),
                ('variation_id', models.IntegerField(default=1)),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('performance_level', models.CharField(max_length=50)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(default='{}')),
            ],
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mocktestsession',
            name='test',
        ),
        migrations.RemoveField(
            model_name='mocktestquestion',
            name='test',
        ),
        migrations.AlterUniqueTogether(
            name='mocktestanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mocktestanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mocktestanswer',
            name='result',
        ),
        migrations.RemoveIndex(
            model_name='mocktestresult',
            name='users_mockt_user_id_15cc8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='mocktestresult',
            name='users_mockt_test_id_c240b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='mocktestresult',
            name='users_mockt_status_5f46ca_idx',
        ),
        migrations.RemoveField(
            model_name='mocktestsession',
            name='result',
        ),
        migrations.RemoveField(
            model_name='mocktestsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onetimekey',
            name='document',
        ),
        migrations.RemoveField(
            model_name='onetimekey',
            name='user',
        ),
        migrations.AddField(
            model_name='usermocktestattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration'),
        ),
        migrations.DeleteModel(
            name='MockTestCategory',
        ),
        migrations.DeleteModel(
            name='MockTestQuestion',
        ),
        migrations.DeleteModel(
            name='MockTestAnswer',
        ),
        migrations.RemoveField(
            model_name='mocktestresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='mocktestresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='MockTestSession',
        ),
        migrations.DeleteModel(
            name='OneTimeKey',
        ),
        migrations.DeleteModel(
            name='MockTest',
        ),
        migrations.DeleteModel(
            name='MockTestResult',
        ),
    ]
