# Generated by Django 6.0.2 on 2026-02-09 05:21

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_usermocktestattempt_remove_mocktest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysislog',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='users.resume'),
        ),
        migrations.CreateModel(
            name='DocumentKeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('key_sent', models.BooleanField(default=False)),
                ('one_time_key', models.CharField(blank=True, max_length=200, null=True)),
                ('used', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_b64', models.CharField(max_length=256)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('encrypted_data', models.FileField(upload_to=users.models.shard_upload_path)),
                ('nonce', models.BinaryField()),
                ('tag', models.BinaryField(blank=True, null=True)),
                ('hash_hex', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shards', to='users.document')),
            ],
        ),
        migrations.CreateModel(
            name='ShardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shard_index', models.PositiveSmallIntegerField()),
                ('key_hash', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shardkeys', to='users.document')),
            ],
        ),
        migrations.DeleteModel(
            name='UserMockTestAttempt',
        ),
    ]
