# Generated by Django 6.0.2 on 2026-02-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_resumeanalysislog_resume_documentkeyrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='institution_name',
            field=models.CharField(choices=[('SCCE', 'SCCE - SREE CHAITANYA COLLEGE OF ENGINEERING'), ('SCIT', 'SCIT - SREE CHAITANYA INSTITUTE OF TECHNOLOGICAL SCIENCES')], default='SCCE', max_length=10),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='college_name',
            field=models.CharField(blank=True, choices=[('SCCE', 'SCCE - SREE CHAITANYA COLLEGE OF ENGINEERING'), ('SCIT', 'SCIT - SREE CHAITANYA INSTITUTE OF TECHNOLOGICAL SCIENCES')], help_text='College (for students only)', max_length=10, null=True),
        ),
    ]
