# Generated by Django 6.0.2 on 2026-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_adminregistration_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
