# Generated by Django 6.0.2 on 2026-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userregistration_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('pic', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('status', models.CharField(default='Activated', max_length=100)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('profession', models.CharField(blank=True, help_text='Profession/Job Title', max_length=100, null=True)),
                ('company', models.CharField(blank=True, help_text='Company/Organization', max_length=200, null=True)),
                ('experience_years', models.FloatField(blank=True, help_text='Years of experience', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('pic', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('status', models.CharField(default='Activated', max_length=100)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('student_id', models.CharField(help_text='Student ID', max_length=50)),
                ('college_name', models.CharField(choices=[('SCCE', 'SCCE - SREE CHAITANYA COLLEGE OF ENGINEERING'), ('SCIT', 'SCIT - SREE CHAITANYA INSTITUTE OF TECHNOLOGICAL SCIENCES')], help_text='College', max_length=10)),
                ('year', models.CharField(help_text='Academic Year', max_length=20)),
                ('branch', models.CharField(help_text='Branch/Specialization', max_length=100)),
                ('academic_marks', models.FloatField(help_text='Academic marks percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
