# Generated by Django 6.0.2 on 2026-02-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_document_documentperformance_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstudent',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='student',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='totp_secret',
        ),
    ]
