# Generated by Django 6.0.2 on 2026-02-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_totp_secret_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstudent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='address',
        ),
    ]
