# Generated by Django 6.0.2 on 2026-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_nonstudent_address_remove_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(default=0, help_text='Number of active backlogs'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='backlog',
            field=models.IntegerField(default=0, help_text='Number of active backlogs (for students only)'),
        ),
    ]
