# Generated by Django 6.0.2 on 2026-02-07 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_cell_id', models.CharField(help_text='Unique identifier for the placement cell', max_length=50, unique=True)),
                ('institution_name', models.CharField(help_text='Name of the institution', max_length=200)),
                ('email', models.EmailField(help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Institution address', null=True)),
                ('website', models.URLField(blank=True, help_text='Institution website', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Institution logo', null=True, upload_to='placement_cell_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the placement cell is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_cell', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Cell',
                'verbose_name_plural': 'Placement Cells',
                'db_table': 'placement_cells',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('drive', 'Placement Drive'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('training', 'Training'), ('other', 'Other')], help_text='Type of activity', max_length=50)),
                ('title', models.CharField(help_text='Activity title', max_length=200)),
                ('description', models.TextField(help_text='Activity description')),
                ('date', models.DateField(help_text='Activity date')),
                ('time', models.TimeField(help_text='Activity time')),
                ('location', models.CharField(help_text='Activity location', max_length=200)),
                ('target_audience', models.CharField(help_text='Target audience', max_length=200)),
                ('max_participants', models.IntegerField(help_text='Maximum participants allowed')),
                ('current_participants', models.IntegerField(default=0, help_text='Current number of participants')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the activity is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Careerlytics.placementcell')),
            ],
            options={
                'verbose_name': 'Placement Activity',
                'verbose_name_plural': 'Placement Activities',
                'db_table': 'placement_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementCellStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Student ID', max_length=50)),
                ('name', models.CharField(help_text='Student name', max_length=100)),
                ('email', models.EmailField(help_text='Student email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Student phone', max_length=20, null=True)),
                ('department', models.CharField(help_text='Student department', max_length=100)),
                ('year', models.IntegerField(help_text='Academic year')),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Student CGPA', max_digits=4)),
                ('skills', models.TextField(blank=True, help_text='Student skills', null=True)),
                ('resume', models.FileField(blank=True, help_text='Student resume file', null=True, upload_to='student_resumes/')),
                ('is_placed', models.BooleanField(default=False, help_text='Whether the student is placed')),
                ('company_placed', models.CharField(blank=True, help_text='Company where student is placed', max_length=200, null=True)),
                ('package_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Package offered in LPA', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Careerlytics.placementcell')),
            ],
            options={
                'verbose_name': 'Placement Cell Student',
                'verbose_name_plural': 'Placement Cell Students',
                'db_table': 'placement_cell_students',
                'ordering': ['-created_at'],
                'unique_together': {('placement_cell', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('job_role', models.CharField(help_text='Job role/position', max_length=200)),
                ('package_offered', models.DecimalField(decimal_places=2, help_text='Package offered in LPA', max_digits=10)),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('placement_date', models.DateField(help_text='Date of placement')),
                ('offer_letter', models.FileField(blank=True, help_text='Offer letter file', null=True, upload_to='offer_letters/')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the placement is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='Careerlytics.placementcell')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_placements', to='Careerlytics.placementcellstudent')),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
                'db_table': 'placements',
                'ordering': ['-placement_date'],
            },
        ),
    ]
