# Generated by Django 6.0.2 on 2026-02-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0001_initial'),
        ('users', '0025_document_documentperformance_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementactivity',
            name='additional_requirements',
            field=models.TextField(blank=True, help_text='Additional requirements', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Application deadline (for drives)', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='classification_rules',
            field=models.JSONField(blank=True, help_text='Classification rules in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name (for drives)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email (for drives)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person (for drives)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone (for drives)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='current_applicants',
            field=models.IntegerField(default=0, help_text='Current number of applicants'),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='drive_date',
            field=models.DateTimeField(blank=True, help_text='Drive date and time (for drives)', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='eligible_departments',
            field=models.TextField(blank=True, help_text='Comma-separated department names', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='eligible_years',
            field=models.TextField(blank=True, help_text='Comma-separated years (1,2,3,4)', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='exam_duration',
            field=models.IntegerField(blank=True, help_text='Exam duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='job_role',
            field=models.CharField(blank=True, help_text='Job role/position (for drives)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='max_applicants',
            field=models.IntegerField(blank=True, default=100, help_text='Maximum applicants allowed', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='package_range',
            field=models.CharField(blank=True, help_text='Package range (for drives)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='questions',
            field=models.JSONField(blank=True, help_text='Test questions in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Drive status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='placementactivity',
            name='activity_type',
            field=models.CharField(choices=[('drive', 'Placement Drive'), ('readiness_test', 'Readiness Test'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('training', 'Training'), ('other', 'Other')], help_text='Type of activity', max_length=50),
        ),
        migrations.CreateModel(
            name='DriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('resume_uploaded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the application')),
                ('student_classification', models.CharField(blank=True, choices=[('placement_ready', 'Placement Ready'), ('needs_improvement', 'Needs Improvement'), ('at_risk', 'At Risk')], max_length=20)),
                ('student_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('student_department', models.CharField(blank=True, max_length=100)),
                ('student_year', models.IntegerField(blank=True, null=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Careerlytics.placementactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_applications', to='users.userregistration')),
            ],
            options={
                'verbose_name': 'Drive Application',
                'verbose_name_plural': 'Drive Applications',
                'db_table': 'drive_applications',
                'ordering': ['-application_date'],
                'unique_together': {('drive', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Test score', max_digits=5)),
                ('total_questions', models.IntegerField(help_text='Total questions in test')),
                ('correct_answers', models.IntegerField(help_text='Correct answers count')),
                ('classification', models.CharField(choices=[('placement_ready', 'Placement Ready'), ('needs_improvement', 'Needs Improvement'), ('at_risk', 'At Risk')], max_length=20)),
                ('started_at', models.DateTimeField(help_text='Test start time')),
                ('completed_at', models.DateTimeField(help_text='Test completion time')),
                ('time_taken', models.IntegerField(help_text='Time taken in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.userregistration')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='Careerlytics.placementactivity')),
            ],
            options={
                'db_table': 'student_test_results',
                'ordering': ['-completed_at'],
                'unique_together': {('test', 'student')},
            },
        ),
    ]
