# Generated by Django 6.0.2 on 2026-02-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0002_add_placement_drive_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcellstudent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the student is active/linked'),
        ),
    ]
