# Generated by Django 6.0.2 on 2026-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0003_placementcellstudent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcellstudent',
            name='backlog',
            field=models.IntegerField(default=0, help_text='Number of active backlogs'),
        ),
    ]
