# Generated by Django 6.0.2 on 2026-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0004_placementcellstudent_backlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementactivity',
            name='classification_rules',
        ),
        migrations.RemoveField(
            model_name='placementcellstudent',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studenttestresult',
            name='classification',
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='at_risk_max',
            field=models.IntegerField(blank=True, help_text='Maximum score for At Risk classification', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='needs_improvement_min',
            field=models.IntegerField(blank=True, help_text='Minimum score for Needs Improvement classification', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='placement_ready_min',
            field=models.IntegerField(blank=True, help_text='Minimum score for Placement Ready classification', null=True),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='test_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', help_text='Test status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='placementcellstudent',
            name='marks_percentage',
            field=models.DecimalField(db_column='cgpa', decimal_places=2, default=0.0, help_text='Student marks percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='aptitude_score',
            field=models.IntegerField(default=0, help_text='Aptitude category score (out of 100)'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='core_subjects_score',
            field=models.IntegerField(default=0, help_text='Core subjects category score (out of 100)'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='english_score',
            field=models.IntegerField(default=0, help_text='English category score (out of 100)'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='readiness_classification',
            field=models.CharField(choices=[('placement_ready', 'Placement Ready'), ('needs_improvement', 'Needs Improvement'), ('at_risk', 'At Risk')], default='needs_improvement', help_text='Student readiness classification', max_length=20),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='reasoning_score',
            field=models.IntegerField(default=0, help_text='Reasoning category score (out of 100)'),
        ),
    ]
