# Generated by Django 6.0.2 on 2026-02-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0005_remove_placementactivity_classification_rules_and_more'),
        ('users', '0027_remove_nonstudent_address_remove_student_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled')], default='disabled', help_text='Test status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Readiness Test',
                'verbose_name_plural': 'Readiness Tests',
                'db_table': 'readiness_tests',
            },
        ),
        migrations.RemoveField(
            model_name='placementactivity',
            name='at_risk_max',
        ),
        migrations.RemoveField(
            model_name='placementactivity',
            name='needs_improvement_min',
        ),
        migrations.RemoveField(
            model_name='placementactivity',
            name='placement_ready_min',
        ),
        migrations.RemoveField(
            model_name='placementactivity',
            name='test_status',
        ),
        migrations.AlterField(
            model_name='placementcellstudent',
            name='marks_percentage',
            field=models.DecimalField(db_column='cgpa', decimal_places=2, help_text='Student marks percentage', max_digits=5),
        ),
        migrations.CreateModel(
            name='ReadinessTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='When student started the test')),
                ('completed_at', models.DateTimeField(help_text='When student completed the test')),
                ('time_taken', models.IntegerField(help_text='Time taken in minutes')),
                ('aptitude_score', models.IntegerField(default=0, help_text='Aptitude questions correct')),
                ('reasoning_score', models.IntegerField(default=0, help_text='Reasoning questions correct')),
                ('english_score', models.IntegerField(default=0, help_text='English questions correct')),
                ('core_score', models.IntegerField(default=0, help_text='Core subject questions correct')),
                ('total_questions', models.IntegerField(default=60, help_text='Total questions in test')),
                ('total_correct', models.IntegerField(default=0, help_text='Total correct answers')),
                ('percentage', models.FloatField(default=0.0, help_text='Overall percentage')),
                ('classification', models.CharField(choices=[('placement_ready', 'Placement Ready'), ('needs_improvement', 'Needs Improvement'), ('at_risk', 'At Risk')], help_text='Student classification based on performance', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Student answers in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_results', to='users.userregistration')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Careerlytics.readinesstest')),
            ],
            options={
                'verbose_name': 'Readiness Test Result',
                'verbose_name_plural': 'Readiness Test Results',
                'db_table': 'readiness_test_results',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'test')},
            },
        ),
    ]
