# Generated by Django 6.0.2 on 2026-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0006_readinesstest_remove_placementactivity_at_risk_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveapplication',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch/Department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='full_name',
            field=models.CharField(blank=True, help_text="Applicant's full name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='gmail',
            field=models.EmailField(blank=True, help_text='Gmail address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='hall_ticket_number',
            field=models.CharField(blank=True, help_text='Hall ticket number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='percentage_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage/CGPA', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
    ]
