# Generated by Django 6.0.2 on 2026-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0007_driveapplication_branch_driveapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveapplication',
            name='student_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
