# Generated by Django 6.0.2 on 2026-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0008_alter_driveapplication_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementactivity',
            name='drive_end_date',
            field=models.DateTimeField(blank=True, help_text='Drive end date and time (for drives)', null=True),
        ),
    ]
