# Generated by Django 6.0.2 on 2026-02-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0009_placementactivity_drive_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTestResult',
        ),
    ]
