# Generated by Django 6.0.2 on 2026-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0010_delete_studenttestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('round_1', 'Round 1'), ('round_2', 'Round 2'), ('round_3', 'Round 3'), ('hr_round', 'HR Round'), ('placed', 'Placed')], default='applied', max_length=20),
        ),
    ]
