# Generated by Django 6.0.2 on 2026-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careerlytics', '0011_alter_driveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='status',
            field=models.CharField(default='placed', help_text='Current status of placement', max_length=50),
        ),
    ]
