# Generated by Django 6.0.2 on 2026-02-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0028_student_backlog_userregistration_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Voice Recording', max_length=200)),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
                ('duration', models.DurationField(help_text='Duration of the recording')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='users.userregistration')),
            ],
            options={
                'verbose_name': 'Voice Recording',
                'verbose_name_plural': 'Voice Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
