# Generated by Django 6.0.2 on 2026-02-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='content_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='fluency_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='jam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='performance_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='question_asked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='soft_skills_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='voice_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
