# Generated by Django 6.0.2 on 2026-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamai', '0002_voicerecording_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
