# Generated by Django 6.0.2 on 2026-02-09 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_alter_resumeanalysislog_resume_documentkeyrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_weeks', models.IntegerField(default=2)),
                ('all_topics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_correction_plan',
            },
        ),
        migrations.CreateModel(
            name='FinalRetest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField(default=60)),
                ('career_recommendation', models.CharField(max_length=50)),
                ('readiness_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.correctionplan')),
            ],
            options={
                'db_table': 'personalizedplan_final_retest',
            },
        ),
        migrations.CreateModel(
            name='PersonalizedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('role', 'Role'), ('language', 'Language')], max_length=20)),
                ('target_role_language', models.CharField(max_length=50)),
                ('current_week', models.IntegerField(default=1)),
                ('current_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_personalized_plan',
            },
        ),
        migrations.AddField(
            model_name='correctionplan',
            name='personalized_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.personalizedplan'),
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('initial', 'Initial'), ('weekly', 'Weekly'), ('final', 'Final'), ('correction', 'Correction')], max_length=20)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('weak_areas', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
                ('personalized_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.personalizedplan')),
            ],
            options={
                'db_table': 'personalizedplan_assessment_result',
            },
        ),
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_week', models.IntegerField()),
                ('current_day', models.IntegerField()),
                ('total_days_completed', models.IntegerField(default=0)),
                ('weekly_tests_passed', models.IntegerField(default=0)),
                ('weekly_tests_failed', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('personalized_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.personalizedplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_plan_progress',
            },
        ),
        migrations.CreateModel(
            name='ResumeImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('before_score', models.IntegerField()),
                ('after_score', models.IntegerField()),
                ('improvement_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_resume_impact',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_days_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_user_streak',
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('xp_to_next_level', models.IntegerField(default=100)),
                ('level_progress', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_user_xp',
            },
        ),
        migrations.CreateModel(
            name='WeakTopicDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weak_topics', models.JSONField(default=dict)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.assessmentresult')),
            ],
            options={
                'db_table': 'personalizedplan_weak_topic_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('skill_focus', models.CharField(max_length=100)),
                ('topics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='locked', max_length=20)),
                ('extra_days_added', models.IntegerField(default=0)),
                ('weak_topics_focus', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personalized_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.personalizedplan')),
            ],
            options={
                'db_table': 'personalizedplan_weekly_plan',
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_reward', models.IntegerField(default=15)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.weeklyplan')),
            ],
            options={
                'db_table': 'personalizedplan_daily_task',
            },
        ),
        migrations.CreateModel(
            name='XPReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('daily_task', 'Daily Task'), ('weekly_test', 'Weekly Test'), ('streak', 'Streak'), ('recovery', 'Recovery'), ('speed', 'Speed'), ('consistency', 'Consistency')], max_length=20)),
                ('xp_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_xp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizedplan.userxp')),
            ],
            options={
                'db_table': 'personalizedplan_xp_reward',
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('week_number', models.IntegerField()),
                ('day_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_daily_activity',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
