# Generated by Django 6.0.2 on 2026-02-09 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizedplan', '0001_initial'),
        ('users', '0020_alter_resumeanalysislog_resume_documentkeyrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('role', 'Role'), ('language', 'Language')], max_length=20)),
                ('target_role_language', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
            options={
                'db_table': 'personalizedplan_assessment_session',
            },
        ),
    ]
