# Generated by Django 6.0.2 on 2026-02-07 16:22

import django.db.models.deletion
import resumeanalysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_remove_userregistration_year_and_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'General Ability'), ('tech_fundamentals', 'Tech Fundamentals'), ('frontend', 'Frontend Specific'), ('backend', 'Backend Specific'), ('devops', 'DevOps Specific'), ('datascience', 'Data Science Specific')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='List of 4 options')),
                ('correct_answer', models.IntegerField(help_text='Index of correct option (0-3)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('tags', models.JSONField(default=list, help_text='Tags for question categorization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_file', models.FileField(upload_to=resumeanalysis.models.resume_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('ats_score', models.IntegerField(help_text='ATS compatibility score (0-100)')),
                ('skills_extracted', models.JSONField(default=list, help_text='List of extracted skills')),
                ('experience_years', models.FloatField(blank=True, help_text='Total years of experience', null=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('skills_match_score', models.IntegerField(default=0, help_text='Skills match score (0-100)')),
                ('experience_score', models.IntegerField(default=0, help_text='Experience relevance score (0-100)')),
                ('education_score', models.IntegerField(default=0, help_text='Education background score (0-100)')),
                ('format_score', models.IntegerField(default=0, help_text='Format and keywords score (0-100)')),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='users.userregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=20)),
                ('resume_score_weighted', models.FloatField(help_text='Resume score contribution (60% weight)')),
                ('quiz_score_weighted', models.FloatField(help_text='Quiz score contribution (40% weight)')),
                ('total_eligibility', models.FloatField(help_text='Total eligibility percentage')),
                ('is_eligible', models.BooleanField(help_text='Eligible for role (>=60%)')),
                ('recommended_roles', models.JSONField(default=list, help_text='List of recommended roles with scores')),
                ('improvement_areas', models.JSONField(default=list, help_text='Areas needing improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.resumeanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_eligibilities', to='users.userregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('match_percentage', models.FloatField(help_text='Match percentage for this role')),
                ('match_reasons', models.JSONField(default=list, help_text='Reasons for this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_roles', to='users.userregistration')),
                ('eligibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.roleeligibility')),
            ],
            options={
                'ordering': ['-match_percentage'],
            },
        ),
        migrations.CreateModel(
            name='RoleQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('devops', 'DevOps Engineer'), ('datascience', 'Data Scientist')], max_length=20)),
                ('total_questions', models.IntegerField(default=30)),
                ('time_limit', models.IntegerField(default=1800, help_text='Time limit in seconds (30 minutes)')),
                ('general_ability_score', models.IntegerField(default=0, help_text='General ability score (0-100)')),
                ('tech_fundamentals_score', models.IntegerField(default=0, help_text='Tech fundamentals score (0-100)')),
                ('role_specific_score', models.IntegerField(default=0, help_text='Role-specific score (0-100)')),
                ('total_score', models.IntegerField(default=0, help_text='Total quiz score (0-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.resumeanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_quizzes', to='users.userregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.rolequiz'),
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.IntegerField(help_text='Index of selected option (0-3)')),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.IntegerField(help_text='Time taken for this question in seconds')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.quizquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='resumeanalysis.rolequiz')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
    ]
