# Generated by Django 6.0.2 on 2026-02-08 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalysis', '0001_initial'),
        ('users', '0016_remove_userregistration_year_and_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleeligibility',
            options={'ordering': ['-eligibility_score']},
        ),
        migrations.RemoveField(
            model_name='roleeligibility',
            name='improvement_areas',
        ),
        migrations.RemoveField(
            model_name='roleeligibility',
            name='quiz_score_weighted',
        ),
        migrations.RemoveField(
            model_name='roleeligibility',
            name='resume_score_weighted',
        ),
        migrations.RemoveField(
            model_name='roleeligibility',
            name='target_role',
        ),
        migrations.RemoveField(
            model_name='roleeligibility',
            name='total_eligibility',
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='eligibility_score',
            field=models.FloatField(default=0.0, help_text='Overall eligibility score (0-100)'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='general_score',
            field=models.FloatField(default=0, help_text='General aptitude score'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='improvement_suggestions',
            field=models.JSONField(default=list, help_text='Specific improvement suggestions'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='resume_score',
            field=models.FloatField(default=0, help_text='Resume analysis score'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='role_name',
            field=models.CharField(default='General', help_text='Target role name', max_length=50),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='role_score',
            field=models.FloatField(default=0, help_text='Role-specific score'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='skill_gaps',
            field=models.JSONField(default=list, help_text='Areas needing improvement'),
        ),
        migrations.AddField(
            model_name='roleeligibility',
            name='tech_score',
            field=models.FloatField(default=0, help_text='Technical knowledge score'),
        ),
        migrations.AlterField(
            model_name='roleeligibility',
            name='is_eligible',
            field=models.BooleanField(help_text='Eligible for role'),
        ),
        migrations.AlterField(
            model_name='roleeligibility',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.rolequiz'),
        ),
        migrations.AlterField(
            model_name='roleeligibility',
            name='recommended_roles',
            field=models.JSONField(default=list, help_text='List of recommended roles'),
        ),
        migrations.AlterField(
            model_name='roleeligibility',
            name='resume_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.resumeanalysis'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(blank=True, help_text='Target role ID if specified', null=True)),
                ('total_questions', models.IntegerField(help_text='Total number of questions')),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes')),
                ('time_taken', models.IntegerField(default=0, help_text='Actual time taken in seconds')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('general_score', models.IntegerField(default=0, help_text='General aptitude score (0-100)')),
                ('tech_score', models.IntegerField(default=0, help_text='Technical knowledge score (0-100)')),
                ('role_score', models.IntegerField(default=0, help_text='Role-specific score (0-100)')),
                ('total_score', models.IntegerField(default=0, help_text='Weighted total score (0-100)')),
                ('questions_answered', models.IntegerField(default=0, help_text='Number of questions answered')),
                ('questions_correct', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('questions_marked_review', models.IntegerField(default=0, help_text='Questions marked for review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='users.userregistration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text='Question identifier', max_length=50)),
                ('question_category', models.CharField(help_text='Question category (general/tech/role)', max_length=20)),
                ('question_text', models.TextField(help_text='Full question text')),
                ('question_options', models.JSONField(help_text='List of question options')),
                ('correct_answer', models.IntegerField(help_text='Index of correct answer')),
                ('selected_answer', models.IntegerField(help_text='Index of selected answer')),
                ('is_correct', models.BooleanField(help_text='Whether the answer is correct')),
                ('is_marked_for_review', models.BooleanField(default=False, help_text='Marked for review by user')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on this question in seconds')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='resumeanalysis.testattempt')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('test_attempt', 'question_id')},
            },
        ),
    ]
