# Generated by Django 6.0.2 on 2026-02-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalysis', '0002_alter_roleeligibility_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='session_question_id',
            field=models.CharField(blank=True, help_text='Question ID for session-based questions', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeanalysis.quizquestion'),
        ),
    ]
