# Generated by Django 6.0.2 on 2026-02-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalysis', '0005_language_alter_mocktest_role_mocktest_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('tests_completed', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='testattempt',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='XP earned from this attempt'),
        ),
    ]
