# Generated by Django 6.0.2 on 2026-02-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeanalysis', '0006_mocktestxp_testattempt_xp_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='category',
            field=models.CharField(blank=True, help_text="Test category (e.g., 'frontend', 'aptitude')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='module_index',
            field=models.IntegerField(blank=True, help_text='Module index for core assessments (0-based)', null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test_type',
            field=models.CharField(default='mock', help_text="Type of test: 'mock' or 'core'", max_length=20),
        ),
    ]
